### ISSUE TITLE
Consider splitting parsdict main() into a few subordinate functions

### ISSUE THREAD

**Issue by alesage** [RBecker262/Python101#2]
From our notes, consider as a style exercise just splitting up main a bit--as we discussed it got a little complicated via adding logging and so on.

(Also this is not a real bug but gives us some practice using "issues" here on GitHub, try to solve this in a new branch, push to origin under a new branch, and we'll merge.)

**Comment by RBecker262** [comment]
Made changes by creating multiple functions with descriptive names and consolidated comments where appropriate. Please review.
