### ISSUE TITLE
Config Argument IS Optional

### ISSUE THREAD

**Issue by RBecker262** [RBecker262/Python101#4]
I added the new command line parameter to optionally specify a different config location. I changed the defaults for both the logging and config files to be inside the repository location rather than the outside path ../DataFiles. Both are in the .gitignore file (along with __pycache__).

Please review. This should complete the items you had on the google docs opened on Thursday unless you find anything during your review. Please submit a pull request when you review and have accepted these changes. :)

**Comment by alesage** [comment]
Hiya, so I'll leave it to you to make the pull request--we'll discuss the change there :) .

**Comment by RBecker262** [comment]
The Config argument IS optional. Try it and see.

**Comment by alesage** [comment]
Confirmed the config option really is optional with merge of #5  :) .

**Comment by RBecker262** [comment]
Awesome! Anything else I need to do as part of the Python 101 suite of classes? Looked through your original roadmap yesterday and saw a couple of things I haven't touched...regex, xml...think I covered everything else except the testing related stuff you want to get more into.

I will be at the meeting tomorrow but I probably won't be there until 6-ish? I have my class getting kids to develop smartphone apps and that goes until 530 in the south loop.
